name: "$(SourceBranchName)+$(BuildID)"

trigger: none
pr: none

resources:
  repositories:
    - repository: common
      type: github
      name: NHSDigital/api-management-utils
      ref: refs/heads/edge
      endpoint: NHSDigital
  pipelines:
    - pipeline: build_pipeline
      source: "Service-Search-Api-Build"
      trigger:
        branches:
          include:
            - refs/tags/v*

pool:
  name: "AWS-ECS"

variables:
  - template: project.yml

extends:
  template: azure/common/apigee-deployment.yml@common
  parameters:
    service_name: ${{ variables.service_name }}
    short_service_name: ${{ variables.short_service_name }}
    service_base_path: ${{ variables.service_base_path }}
    prod_requires_approval: true
    prod_producer_approval: true
    apigee_deployments:
      - environment: internal-dev
        jinja_templates:
          HEALTHCHECK_URL: ${{ variables.healthcheck_url_stag }}
        post_deploy:
         - template: ./run-integration-tests.yml
      - environment: internal-qa
        jinja_templates:
          HEALTHCHECK_URL: ${{ variables.healthcheck_url_stag }}
        post_deploy:
         - template: ./run-integration-tests.yml
      - environment: ref
        jinja_templates:
          HEALTHCHECK_URL: ${{ variables.healthcheck_url_stag }}  
        post_deploy:
         - template: ./run-integration-tests.yml
      - environment: internal-qa-sandbox
        proxy_path: sandbox
        post_deploy:
         - template: ./run-sandbox-tests.yml
      - environment: internal-dev-sandbox
        jinja_templates:
          HEALTHCHECK_URL: ' '
        proxy_path: sandbox
        post_deploy:
         - template: ./run-sandbox-tests.yml
      - environment: sandbox
        proxy_path: sandbox
        depends_on:
          - internal_dev_sandbox
          - internal_qa_sandbox
        # post_deploy:
        #  - template: ./templates/run-smoke-tests.yml
      - environment: int
        jinja_templates:
          HEALTHCHECK_URL: ${{ variables.healthcheck_url_stag }}
        depends_on:
          - internal_dev
          - internal_qa
       # post_deploy:
       #   - template: ./templates/run-smoke-tests.yml
      - environment: prod
        depends_on:              # which environments to depend on before deploying
          - int
       # post_deploy:
       #   - template: ./templates/run-smoke-tests.yml
        jinja_templates:         # any additional values you need to template into your proxy at deploy time
          REQUIRE_ASID: true
          PDS_TARGET_SERVER: spine-demographics
