#!/bin/bash

# Build the examples into the spec via speccy
redocly bundle ./specification/service-search-api.yaml > ./specification/redocly-output.yaml

# Convert the full spec into a postman collection
openapi2postmanv2 -s ./specification/redocly-output.yaml -o ./specification/postman-collection.json -p -O folderStrategy=Tags,includeAuthInfoInExample=false

# Clean up the file generated by speccy
rm ./specification/redocly-output.yaml
